# Generated by Django 5.0.1 on 2024-02-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Product Name")),
                ("price", models.IntegerField(verbose_name="Product Price")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Product Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "db_table": "product",
            },
        ),
    ]
