# Generated by Django 5.0.1 on 2024-01-03 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hello_db", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="hello",
            table="hello",
        ),
    ]
